version: '3'
services:
  db: 
    image: mysql:8.0
    container_name: db_mysql_c
    ports:
      - '3080:3306'
    environment:
      MYSQL_DATABASE: test_typeorm
      MYSQL_ROOT_PASSWORD: 0miguel15
    volumes:
      - ./mysql:/var/lib/mysql
  backend:
    build: ./
    container_name: nodeserver_c
    ports:
      - '5000:5000'
    environment:
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
    depends_on:
      - db
volumes:
  mysql: